### ISSUE TITLE
[IMPROVEMENTS] Error during startup

### ISSUE THREAD

**Issue by vita55555** [Ziocash/CBSInterpreter#1]
Hello,
I'm trying to run applications on Windows 11 24H2,
I get an error:

`Application: CBSInterpreter.WPF.exe
CoreCLR Version: 6.0.3524.45918
.NET Version: 6.0.35
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.IOException: The process cannot access the file 'C:\Windows\Logs\CBS\CBS.log' because it is being used by another process.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.StreamReader..ctor(String path)
   at CBSInterpreter.Core.CBSReader..ctor() in C:\Users\Simone Gattini\Source\Repos\CBSInterpreter\CBSInterpreter\Core\CBSReader.cs:line 22
   at CBSInterpreter.WPF.MainWindow..ctor() in C:\Users\Simone Gattini\Source\Repos\CBSInterpreter\CBSInterpreter.WPF\MainWindow.xaml.cs:line 18
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at CBSInterpreter.WPF.App.OnStartup(StartupEventArgs e) in C:\Users\Simone Gattini\Source\Repos\CBSInterpreter\CBSInterpreter.WPF\App.xaml.cs:line 30
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at CBSInterpreter.WPF.App.Main() in C:\Users\Simone Gattini\Source\Repos\CBSInterpreter\CBSInterpreter.WPF\obj\Release\net6.0-windows\App.g.cs:line 52
`

`Имя сбойного приложения: CBSInterpreter.WPF.exe, версия: 1.0.0.0, метка времени: 0x61e1d8d9
Имя сбойного модуля: KERNELBASE.dll, версия: 10.0.26100.1882, метка времени: 0xdebc683b
Код исключения: 0xe0434352
Смещение ошибки: 0x00000000000c83ea
Идентификатор сбойного процесса: 0x7424
Время запуска сбойного приложения: 0x1DB1D4459FD5354
Путь сбойного приложения: C:\Tool\SFC\portable\portable\CBSInterpreter.WPF.exe
Путь сбойного модуля: C:\WINDOWS\System32\KERNELBASE.dll
Идентификатор отчета: 8162d24b-1df6-4474-a781-cd56b002f8b7
Полное имя сбойного пакета: 
Код приложения, связанного со сбойным пакетом: `

Контейнер ошибки 1590530254438088613, тип 4
Имя события: APPCRASH
Отклик: Нет данных
Идентификатор CAB: 0

Сигнатура проблемы:
P1: CBSInterpreter.WPF.exe
P2: 1.0.0.0
P3: 61e1d8d9
P4: KERNELBASE.dll
P5: 10.0.26100.1882
P6: debc683b
P7: e0434352
P8: 00000000000c83ea
P9: 
P10: 

Вложенные файлы:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.b93842b5-b0a7-4a97-9262-bdc0424bc296.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.42e98edc-207d-4bbb-aed6-f2ae8e8779f5.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.93ff38e5-a1d2-4fd6-9e9a-ab0dcb2316b7.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.e932bdfa-a6d4-4e5e-8798-31afb60ba4cc.tmp.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.39bd5aea-c113-4bca-ab5f-ce349cbcbf69.tmp.xml

Эти файлы можно найти здесь:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_CBSInterpreter.W_d379f9997ea14fc0cf592499f45b6d74dd2a1b3f_8aa1f4e1_e1f61a0e-07a9-43da-b377-38fd5f3cbbde

Символ анализа: 
Повторный поиск решения: 0
Идентификатор отчета: 8162d24b-1df6-4474-a781-cd56b002f8b7
Состояние отчета: 268435456
Хэшированный контейнер: 44f4752a66a3e37e6612b2d6e44b3fa5
Идентификатор GUID CAB: 0

**Comment by Ziocash** [comment]
I already encountered this issue before, currently I'm resuming this project after a long time away, so I'll check this issue and maybe get a workaround.

**Comment by Ziocash** [comment]
Could you try this release? Should be working.
https://github.com/Ziocash/CBSInterpreter/releases/tag/pre-release-v2

I'll leave this issue open for further improvements on in-use files
